export const CACHE_NO_EXPIRE = 0;
const CACHE_ID_BY_USERNAME_KEY = 'CACHE_ID_BY_USERNAME_KEY';
const AGGREGATE_KEY = 'AGGREGATE_KEY';

export const CACHE_KEYS = {
  AGGREGATE_KEY,
  CACHE_ID_BY_USERNAME_KEY,
};
