version: '3.4'

services:
  hangman-projections:
    container_name: hangman-projections
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PROJECTIONS_CREDENTIALS_PASSWORD}
      MYSQL_DATABASE: ${PROJECTIONS_DATABASE}
      MYSQL_TCP_PORT: ${PROJECTIONS_PORT}
    networks:
      - backend
    ports:
      - ${PROJECTIONS_PORT}:${PROJECTIONS_PORT}
    volumes:
      - type: volume
        source: projections-volume-data
        target: /var/lib/projections

  hangman-eventstore:
    container_name: hangman-eventstore
    image: eventstore/eventstore:20.6.1-buster-slim
    env_file:
      - ./.env
    ports:
      - '${EVENTSTORE_EXT_TCP_PORT}:1113'
      - '${EVENTSTORE_EXT_HTTP_PORT}:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - backend

  hangman-position:
    container_name: hangman-position
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${STORE_STATE_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${STORE_STATE_PASSWORD}'
    ports:
      - ${STORE_STATE_PORT}:${STORE_STATE_PORT}
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8091:8091
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${STORE_STATE_USERNAME}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${STORE_STATE_PASSWORD}'
      ME_CONFIG_MONGODB_URL: mongodb://${STORE_STATE_USERNAME}:${STORE_STATE_PASSWORD}@hangman-position:${STORE_STATE_PORT}/
    networks:
      - backend

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - backend

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
        - redis    
    networks:
      - backend  

  hangman:
    container_name: hangman
    build:
      context: '.'
    env_file:
      - ./.env
    command: ${CONTAINER_COMMAND}
    restart: always
    deploy:
      mode: replicated
      replicas: ${CONTAINER_SCALE}
      # above is ignored by dc up and dc run (only when deploy to swarm with docker stack deploy)
    depends_on:
      - hangman-projections
      - hangman-eventstore
      # service wont be started before this service is running
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7070']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - '${APP_PORT}:${CONTAINER_PORT}'
    volumes:
      - './src:/app/src'
    links:
      - hangman-projections
      # by default, any service can reach any other service at that service’s name.
    networks:
      - backend

volumes:
  projections-volume-data:
  eventstore-volume-data:
  eventstore-volume-logs:

networks:
  backend:
    driver: bridge
