name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker compose build
    - name: Run the Docker images
      run: docker compose up -d
    - name: Clean up the Docker images
      run: docker compose stop && docker compose remove
